### ISSUE TITLE
Proposal Feedback

### ISSUE THREAD

**Issue by ryeduru** [zalu224/506-project#1]
Great job on the proposal! The objectives are clear and relevant, and using NYC Open Data for both air quality and tree census data is a solid choice. Just a suggestion: make sure to detail how you’ll handle any geographic alignment issues between the datasets—differences in coordinate systems or granularity can be tricky. Your use of linear regression and geospatial clustering methods makes sense, but consider mentioning advanced geospatial techniques like spatial autocorrelation for a more nuanced analysis. Validation using cross-validation and holding out city regions is a strong approach; just ensure the regions are representative of the city’s diversity. Overall, it’s a well-structured proposal—just refine the data handling section a bit, and you’re good to go!

**Comment by YuZW42** [comment]
Hi, I have create a PR based on the comments provided and I tried to update the read me given the new information. Thank you for your feedback, they are really helpful. Let me know if I missed something and I would happy to make the according change. Thanks again.
